package net.ebaolife.husqvarna.business.sales.entity;


// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * SArea generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_area", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SArea implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -3243118177073067755L;
private String areaid;
  private String name;
  private Set<SProvince> SProvinces = new HashSet<SProvince>(0);

  public SArea() {}


  public SArea(String areaid) {
    this.areaid = areaid;
  }

  public SArea(String areaid, String name, Set<SProvince> SProvinces) {
    this.areaid = areaid;
    this.name = name;
    this.SProvinces = SProvinces;
  }

  @Id


  @Column(name = "areaid", unique = true, nullable = false, length = 2)
  public String getAreaid() {
    return this.areaid;
  }

  public void setAreaid(String areaid) {
    this.areaid = areaid;
  }


  @Column(name = "name", unique = true, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SArea")
  public Set<SProvince> getSProvinces() {
    return this.SProvinces;
  }

  public void setSProvinces(Set<SProvince> SProvinces) {
    this.SProvinces = SProvinces;
  }



}


