package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * SCity generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_city", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SCity implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -6049645986065606154L;
private String cityid;
  private SProvince SProvince;
  private String name;
  private Boolean ismain;
  private Boolean isimportant;
  private String remark;
  private Set<SCustomer> SCustomers = new HashSet<SCustomer>(0);

  public SCity() {}


  public SCity(String cityid, SProvince SProvince, String name) {
    this.cityid = cityid;
    this.SProvince = SProvince;
    this.name = name;
  }

  public SCity(String cityid, SProvince SProvince, String name, Boolean ismain, Boolean isimportant, String remark,
      Set<SCustomer> SCustomers) {
    this.cityid = cityid;
    this.SProvince = SProvince;
    this.name = name;
    this.ismain = ismain;
    this.isimportant = isimportant;
    this.remark = remark;
    this.SCustomers = SCustomers;
  }

  @Id


  @Column(name = "cityid", unique = true, nullable = false, length = 4)
  public String getCityid() {
    return this.cityid;
  }

  public void setCityid(String cityid) {
    this.cityid = cityid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "provinceid", nullable = false)
  public SProvince getSProvince() {
    return this.SProvince;
  }

  public void setSProvince(SProvince SProvince) {
    this.SProvince = SProvince;
  }


  @Column(name = "name", unique = true, nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Column(name = "ismain")
  public Boolean getIsmain() {
    return this.ismain;
  }

  public void setIsmain(Boolean ismain) {
    this.ismain = ismain;
  }


  @Column(name = "isimportant")
  public Boolean getIsimportant() {
    return this.isimportant;
  }

  public void setIsimportant(Boolean isimportant) {
    this.isimportant = isimportant;
  }


  @Column(name = "remark", length = 200)
  public String getRemark() {
    return this.remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SCity")
  public Set<SCustomer> getSCustomers() {
    return this.SCustomers;
  }

  public void setSCustomers(Set<SCustomer> SCustomers) {
    this.SCustomers = SCustomers;
  }



}


