package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SCustomer generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_customer", catalog = "sales")
public class SCustomer implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -4807373606984500832L;
private String customerid;
  private SCity SCity;
  private SRate SRate;
  private STrade STrade;
  private String name;
  private String address;
  private String telnumber;
  private String linkmen;
  private String creater;
  private Date createdate;
  private String lastmodifier;
  private Date lastmodifydate;
  private Set<SOrder> SOrders = new HashSet<SOrder>(0);

  public SCustomer() {}


  public SCustomer(String customerid, SCity SCity, SRate SRate, STrade STrade, String name) {
    this.customerid = customerid;
    this.SCity = SCity;
    this.SRate = SRate;
    this.STrade = STrade;
    this.name = name;
  }

  public SCustomer(String customerid, SCity SCity, SRate SRate, STrade STrade, String name, String address,
      String telnumber, String linkmen, String creater, Date createdate, String lastmodifier, Date lastmodifydate,
      Set<SOrder> SOrders) {
    this.customerid = customerid;
    this.SCity = SCity;
    this.SRate = SRate;
    this.STrade = STrade;
    this.name = name;
    this.address = address;
    this.telnumber = telnumber;
    this.linkmen = linkmen;
    this.creater = creater;
    this.createdate = createdate;
    this.lastmodifier = lastmodifier;
    this.lastmodifydate = lastmodifydate;
    this.SOrders = SOrders;
  }

  @Id


  @Column(name = "customerid", unique = true, nullable = false, length = 40)
  public String getCustomerid() {
    return this.customerid;
  }

  public void setCustomerid(String customerid) {
    this.customerid = customerid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "cityid", nullable = false)
  public SCity getSCity() {
    return this.SCity;
  }

  public void setSCity(SCity SCity) {
    this.SCity = SCity;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "rateid", nullable = false)
  public SRate getSRate() {
    return this.SRate;
  }

  public void setSRate(SRate SRate) {
    this.SRate = SRate;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "tradeid", nullable = false)
  public STrade getSTrade() {
    return this.STrade;
  }

  public void setSTrade(STrade STrade) {
    this.STrade = STrade;
  }


  @Column(name = "name", nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Column(name = "address", length = 40)
  public String getAddress() {
    return this.address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  @Column(name = "telnumber", length = 40)
  public String getTelnumber() {
    return this.telnumber;
  }

  public void setTelnumber(String telnumber) {
    this.telnumber = telnumber;
  }


  @Column(name = "linkmen", length = 40)
  public String getLinkmen() {
    return this.linkmen;
  }

  public void setLinkmen(String linkmen) {
    this.linkmen = linkmen;
  }


  @Column(name = "creater", length = 40)
  public String getCreater() {
    return this.creater;
  }

  public void setCreater(String creater) {
    this.creater = creater;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdate", length = 19)
  public Date getCreatedate() {
    return this.createdate;
  }

  public void setCreatedate(Date createdate) {
    this.createdate = createdate;
  }


  @Column(name = "lastmodifier", length = 40)
  public String getLastmodifier() {
    return this.lastmodifier;
  }

  public void setLastmodifier(String lastmodifier) {
    this.lastmodifier = lastmodifier;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lastmodifydate", length = 19)
  public Date getLastmodifydate() {
    return this.lastmodifydate;
  }

  public void setLastmodifydate(Date lastmodifydate) {
    this.lastmodifydate = lastmodifydate;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SCustomer")
  public Set<SOrder> getSOrders() {
    return this.SOrders;
  }

  public void setSOrders(Set<SOrder> SOrders) {
    this.SOrders = SOrders;
  }



}


