package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;

/**
 * SDepartmenttarget generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_departmenttarget", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = {
    "salesyear", "salesdepartmentid"}))
public class SDepartmenttarget implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -6487558601572768543L;
private String targetid;
  private SSalesdepartment SSalesdepartment;
  private int salesyear;
  private double targetamount;

  public SDepartmenttarget() {}

  public SDepartmenttarget(String targetid, SSalesdepartment SSalesdepartment, int salesyear, double targetamount) {
    this.targetid = targetid;
    this.SSalesdepartment = SSalesdepartment;
    this.salesyear = salesyear;
    this.targetamount = targetamount;
  }

  @Id


  @Column(name = "targetid", unique = true, nullable = false, length = 40)
  public String getTargetid() {
    return this.targetid;
  }

  public void setTargetid(String targetid) {
    this.targetid = targetid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "salesdepartmentid", nullable = false)
  public SSalesdepartment getSSalesdepartment() {
    return this.SSalesdepartment;
  }

  public void setSSalesdepartment(SSalesdepartment SSalesdepartment) {
    this.SSalesdepartment = SSalesdepartment;
  }


  @Column(name = "salesyear", nullable = false)
  public int getSalesyear() {
    return this.salesyear;
  }

  public void setSalesyear(int salesyear) {
    this.salesyear = salesyear;
  }


  @Column(name = "targetamount", nullable = false, precision = 22, scale = 0)
  public double getTargetamount() {
    return this.targetamount;
  }

  public void setTargetamount(double targetamount) {
    this.targetamount = targetamount;
  }



}


