package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;

/**
 * SOrderdetail generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_orderdetail", catalog = "sales")
public class SOrderdetail implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -2368464366920519764L;
private String orderdetailid;
  private SOrder SOrder;
  private SProduct SProduct;
  private String name;
  private Float numbers;
  private Float unitprice;
  private Double amount;
  private String creater;
  private Date createdate;
  private String lastmodifier;
  private Date lastmodifydate;

  public SOrderdetail() {}


  public SOrderdetail(String orderdetailid, SOrder SOrder, SProduct SProduct, String name) {
    this.orderdetailid = orderdetailid;
    this.SOrder = SOrder;
    this.SProduct = SProduct;
    this.name = name;
  }

  public SOrderdetail(String orderdetailid, SOrder SOrder, SProduct SProduct, String name, Float numbers,
      Float unitprice, Double amount, String creater, Date createdate, String lastmodifier, Date lastmodifydate) {
    this.orderdetailid = orderdetailid;
    this.SOrder = SOrder;
    this.SProduct = SProduct;
    this.name = name;
    this.numbers = numbers;
    this.unitprice = unitprice;
    this.amount = amount;
    this.creater = creater;
    this.createdate = createdate;
    this.lastmodifier = lastmodifier;
    this.lastmodifydate = lastmodifydate;
  }

  @Id


  @Column(name = "orderdetailid", unique = true, nullable = false, length = 40)
  public String getOrderdetailid() {
    return this.orderdetailid;
  }

  public void setOrderdetailid(String orderdetailid) {
    this.orderdetailid = orderdetailid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "orderid", nullable = false)
  public SOrder getSOrder() {
    return this.SOrder;
  }

  public void setSOrder(SOrder SOrder) {
    this.SOrder = SOrder;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "productid", nullable = false)
  public SProduct getSProduct() {
    return this.SProduct;
  }

  public void setSProduct(SProduct SProduct) {
    this.SProduct = SProduct;
  }


  @Column(name = "name", nullable = false, length = 40)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Column(name = "numbers", precision = 12, scale = 0)
  public Float getNumbers() {
    return this.numbers;
  }

  public void setNumbers(Float numbers) {
    this.numbers = numbers;
  }


  @Column(name = "unitprice", precision = 12, scale = 0)
  public Float getUnitprice() {
    return this.unitprice;
  }

  public void setUnitprice(Float unitprice) {
    this.unitprice = unitprice;
  }


  @Column(name = "amount", precision = 22, scale = 0)
  public Double getAmount() {
    return this.amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }


  @Column(name = "creater", length = 40)
  public String getCreater() {
    return this.creater;
  }

  public void setCreater(String creater) {
    this.creater = creater;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdate", length = 19)
  public Date getCreatedate() {
    return this.createdate;
  }

  public void setCreatedate(Date createdate) {
    this.createdate = createdate;
  }


  @Column(name = "lastmodifier", length = 40)
  public String getLastmodifier() {
    return this.lastmodifier;
  }

  public void setLastmodifier(String lastmodifier) {
    this.lastmodifier = lastmodifier;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lastmodifydate", length = 19)
  public Date getLastmodifydate() {
    return this.lastmodifydate;
  }

  public void setLastmodifydate(Date lastmodifydate) {
    this.lastmodifydate = lastmodifydate;
  }



}


