package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SProduct generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_product", catalog = "sales")
public class SProduct implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -6226831018305732410L;
private String productid;
  private SProducttype SProducttype;
  private SProvince SProvince;
  private String pcode;
  private String name;
  private Float costprice;
  private String ptype;
  private String creater;
  private Date createdate;
  private String lastmodifier;
  private Date lastmodifydate;
  private Set<SOrderdetail> SOrderdetails = new HashSet<SOrderdetail>(0);

  public SProduct() {}


  public SProduct(String productid, SProducttype SProducttype, String pcode, String name) {
    this.productid = productid;
    this.SProducttype = SProducttype;
    this.pcode = pcode;
    this.name = name;
  }

  public SProduct(String productid, SProducttype SProducttype, SProvince SProvince, String pcode, String name,
      Float costprice, String ptype, String creater, Date createdate, String lastmodifier, Date lastmodifydate,
      Set<SOrderdetail> SOrderdetails) {
    this.productid = productid;
    this.SProducttype = SProducttype;
    this.SProvince = SProvince;
    this.pcode = pcode;
    this.name = name;
    this.costprice = costprice;
    this.ptype = ptype;
    this.creater = creater;
    this.createdate = createdate;
    this.lastmodifier = lastmodifier;
    this.lastmodifydate = lastmodifydate;
    this.SOrderdetails = SOrderdetails;
  }

  @Id


  @Column(name = "productid", unique = true, nullable = false, length = 40)
  public String getProductid() {
    return this.productid;
  }

  public void setProductid(String productid) {
    this.productid = productid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "producttypeid", nullable = false)
  public SProducttype getSProducttype() {
    return this.SProducttype;
  }

  public void setSProducttype(SProducttype SProducttype) {
    this.SProducttype = SProducttype;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "provinceid")
  public SProvince getSProvince() {
    return this.SProvince;
  }

  public void setSProvince(SProvince SProvince) {
    this.SProvince = SProvince;
  }


  @Column(name = "pcode", nullable = false, length = 40)
  public String getPcode() {
    return this.pcode;
  }

  public void setPcode(String pcode) {
    this.pcode = pcode;
  }


  @Column(name = "name", nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Column(name = "costprice", precision = 12, scale = 0)
  public Float getCostprice() {
    return this.costprice;
  }

  public void setCostprice(Float costprice) {
    this.costprice = costprice;
  }


  @Column(name = "ptype", length = 40)
  public String getPtype() {
    return this.ptype;
  }

  public void setPtype(String ptype) {
    this.ptype = ptype;
  }


  @Column(name = "creater", length = 40)
  public String getCreater() {
    return this.creater;
  }

  public void setCreater(String creater) {
    this.creater = creater;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "createdate", length = 19)
  public Date getCreatedate() {
    return this.createdate;
  }

  public void setCreatedate(Date createdate) {
    this.createdate = createdate;
  }


  @Column(name = "lastmodifier", length = 40)
  public String getLastmodifier() {
    return this.lastmodifier;
  }

  public void setLastmodifier(String lastmodifier) {
    this.lastmodifier = lastmodifier;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lastmodifydate", length = 19)
  public Date getLastmodifydate() {
    return this.lastmodifydate;
  }

  public void setLastmodifydate(Date lastmodifydate) {
    this.lastmodifydate = lastmodifydate;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SProduct")
  public Set<SOrderdetail> getSOrderdetails() {
    return this.SOrderdetails;
  }

  public void setSOrderdetails(Set<SOrderdetail> SOrderdetails) {
    this.SOrderdetails = SOrderdetails;
  }



}


