package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * SProducttype generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_producttype", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SProducttype implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -4732262287579648603L;
private String producttypeid;
  private String name;
  private Set<SProduct> SProducts = new HashSet<SProduct>(0);

  public SProducttype() {}


  public SProducttype(String producttypeid, String name) {
    this.producttypeid = producttypeid;
    this.name = name;
  }

  public SProducttype(String producttypeid, String name, Set<SProduct> SProducts) {
    this.producttypeid = producttypeid;
    this.name = name;
    this.SProducts = SProducts;
  }

  @Id


  @Column(name = "producttypeid", unique = true, nullable = false, length = 2)
  public String getProducttypeid() {
    return this.producttypeid;
  }

  public void setProducttypeid(String producttypeid) {
    this.producttypeid = producttypeid;
  }


  @Column(name = "name", unique = true, nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SProducttype")
  public Set<SProduct> getSProducts() {
    return this.SProducts;
  }

  public void setSProducts(Set<SProduct> SProducts) {
    this.SProducts = SProducts;
  }



}


