package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;

/**
 * SSalesmantarget generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_salesmantarget", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = {
    "salesyear", "salesmanid"}))
public class SSalesmantarget implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = 5608142930017497556L;
private String mantargetid;
  private SSalesman SSalesman;
  private int salesyear;
  private double targetamount;

  public SSalesmantarget() {}

  public SSalesmantarget(String mantargetid, SSalesman SSalesman, int salesyear, double targetamount) {
    this.mantargetid = mantargetid;
    this.SSalesman = SSalesman;
    this.salesyear = salesyear;
    this.targetamount = targetamount;
  }

  @Id


  @Column(name = "mantargetid", unique = true, nullable = false, length = 40)
  public String getMantargetid() {
    return this.mantargetid;
  }

  public void setMantargetid(String mantargetid) {
    this.mantargetid = mantargetid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "salesmanid", nullable = false)
  public SSalesman getSSalesman() {
    return this.SSalesman;
  }

  public void setSSalesman(SSalesman SSalesman) {
    this.SSalesman = SSalesman;
  }


  @Column(name = "salesyear", nullable = false)
  public int getSalesyear() {
    return this.salesyear;
  }

  public void setSalesyear(int salesyear) {
    this.salesyear = salesyear;
  }


  @Column(name = "targetamount", nullable = false, precision = 22, scale = 0)
  public double getTargetamount() {
    return this.targetamount;
  }

  public void setTargetamount(double targetamount) {
    this.targetamount = targetamount;
  }



}


