package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SSalesman generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_salesman", catalog = "sales")
public class SSalesman implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = -1395014461794827874L;
private String salesmanid;
  private SSalesdepartment SSalesdepartment;
  private String name;
  private Date birthday;
  private String sex;
  private Set<SOrder> SOrders = new HashSet<SOrder>(0);
  private Set<SSalesmantarget> SSalesmantargets = new HashSet<SSalesmantarget>(0);

  public SSalesman() {}


  public SSalesman(String salesmanid, SSalesdepartment SSalesdepartment, String name) {
    this.salesmanid = salesmanid;
    this.SSalesdepartment = SSalesdepartment;
    this.name = name;
  }

  public SSalesman(String salesmanid, SSalesdepartment SSalesdepartment, String name, Date birthday, String sex,
      Set<SOrder> SOrders, Set<SSalesmantarget> SSalesmantargets) {
    this.salesmanid = salesmanid;
    this.SSalesdepartment = SSalesdepartment;
    this.name = name;
    this.birthday = birthday;
    this.sex = sex;
    this.SOrders = SOrders;
    this.SSalesmantargets = SSalesmantargets;
  }

  @Id


  @Column(name = "salesmanid", unique = true, nullable = false, length = 40)
  public String getSalesmanid() {
    return this.salesmanid;
  }

  public void setSalesmanid(String salesmanid) {
    this.salesmanid = salesmanid;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "salesdepartmentid", nullable = false)
  public SSalesdepartment getSSalesdepartment() {
    return this.SSalesdepartment;
  }

  public void setSSalesdepartment(SSalesdepartment SSalesdepartment) {
    this.SSalesdepartment = SSalesdepartment;
  }


  @Column(name = "name", nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "birthday", length = 10)
  public Date getBirthday() {
    return this.birthday;
  }

  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }


  @Column(name = "sex")
  public String getSex() {
    return this.sex;
  }

  public void setSex(String sex) {
    this.sex = sex;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SSalesman")
  public Set<SOrder> getSOrders() {
    return this.SOrders;
  }

  public void setSOrders(Set<SOrder> SOrders) {
    this.SOrders = SOrders;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SSalesman")
  public Set<SSalesmantarget> getSSalesmantargets() {
    return this.SSalesmantargets;
  }

  public void setSSalesmantargets(Set<SSalesmantarget> SSalesmantargets) {
    this.SSalesmantargets = SSalesmantargets;
  }



}


