package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * SSalesdepartment generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_salesdepartment", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class SSalesdepartment implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = 799344988141433148L;
private String salesdepartmentid;
  private String name;
  private Set<SSalesman> SSalesmans = new HashSet<SSalesman>(0);
  private Set<SDepartmenttarget> SDepartmenttargets = new HashSet<SDepartmenttarget>(0);

  public SSalesdepartment() {}


  public SSalesdepartment(String salesdepartmentid, String name) {
    this.salesdepartmentid = salesdepartmentid;
    this.name = name;
  }

  public SSalesdepartment(String salesdepartmentid, String name, Set<SSalesman> SSalesmans,
      Set<SDepartmenttarget> SDepartmenttargets) {
    this.salesdepartmentid = salesdepartmentid;
    this.name = name;
    this.SSalesmans = SSalesmans;
    this.SDepartmenttargets = SDepartmenttargets;
  }

  @Id


  @Column(name = "salesdepartmentid", unique = true, nullable = false, length = 4)
  public String getSalesdepartmentid() {
    return this.salesdepartmentid;
  }

  public void setSalesdepartmentid(String salesdepartmentid) {
    this.salesdepartmentid = salesdepartmentid;
  }


  @Column(name = "name", unique = true, nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SSalesdepartment")
  public Set<SSalesman> getSSalesmans() {
    return this.SSalesmans;
  }

  public void setSSalesmans(Set<SSalesman> SSalesmans) {
    this.SSalesmans = SSalesmans;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "SSalesdepartment")
  public Set<SDepartmenttarget> getSDepartmenttargets() {
    return this.SDepartmenttargets;
  }

  public void setSDepartmenttargets(Set<SDepartmenttarget> SDepartmenttargets) {
    this.SDepartmenttargets = SDepartmenttargets;
  }



}


