package net.ebaolife.husqvarna.business.sales.entity;
// default package
// Generated 2017-1-11 15:51:24 by Hibernate Tools 5.2.0.Beta1


import org.hibernate.annotations.DynamicUpdate;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * STrade generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "s_trade", catalog = "sales", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class STrade implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = 6905355486943264095L;
private String tradeid;
  private String name;
  private Set<SCustomer> SCustomers = new HashSet<SCustomer>(0);

  public STrade() {}


  public STrade(String tradeid, String name) {
    this.tradeid = tradeid;
    this.name = name;
  }

  public STrade(String tradeid, String name, Set<SCustomer> SCustomers) {
    this.tradeid = tradeid;
    this.name = name;
    this.SCustomers = SCustomers;
  }

  @Id


  @Column(name = "tradeid", unique = true, nullable = false, length = 4)
  public String getTradeid() {
    return this.tradeid;
  }

  public void setTradeid(String tradeid) {
    this.tradeid = tradeid;
  }


  @Column(name = "name", unique = true, nullable = false, length = 50)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "STrade")
  public Set<SCustomer> getSCustomers() {
    return this.SCustomers;
  }

  public void setSCustomers(Set<SCustomer> SCustomers) {
    this.SCustomers = SCustomers;
  }



}


